// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL6aKYbTevYIIgq1GWxkW56PMrF2lUIkg',
    appId: '1:701298575953:web:9105394f1570e430984670',
    messagingSenderId: '701298575953',
    projectId: 'db-flutter-miage-vinted',
    authDomain: 'db-flutter-miage-vinted.firebaseapp.com',
    storageBucket: 'db-flutter-miage-vinted.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZxa0TzAYx99jsm-evLXDp9COA6-OLmug',
    appId: '1:701298575953:android:65b8dfe3f4b2e9b2984670',
    messagingSenderId: '701298575953',
    projectId: 'db-flutter-miage-vinted',
    storageBucket: 'db-flutter-miage-vinted.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFLlhHnH5eiPK-eRO3tnx9jKRO91VdjzA',
    appId: '1:701298575953:ios:37e69c798715a818984670',
    messagingSenderId: '701298575953',
    projectId: 'db-flutter-miage-vinted',
    storageBucket: 'db-flutter-miage-vinted.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFLlhHnH5eiPK-eRO3tnx9jKRO91VdjzA',
    appId: '1:701298575953:ios:37e69c798715a818984670',
    messagingSenderId: '701298575953',
    projectId: 'db-flutter-miage-vinted',
    storageBucket: 'db-flutter-miage-vinted.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL6aKYbTevYIIgq1GWxkW56PMrF2lUIkg',
    appId: '1:701298575953:web:97f7eeb54736559b984670',
    messagingSenderId: '701298575953',
    projectId: 'db-flutter-miage-vinted',
    authDomain: 'db-flutter-miage-vinted.firebaseapp.com',
    storageBucket: 'db-flutter-miage-vinted.firebasestorage.app',
  );

}